wrapper:
  config_file_name: v16_casual_walk.yaml 
  lidar_topic: /points_raw
  imu_topic:  /imu_raw
  lidar_type: 1 # 0)avia 1) velodyne
  point_skip: 5

front_end:
  extrin_r: [-1,0,0,
            0,1,0,
            0,0,-1]
  extrin_t: [0,0,0]
  enable_record: false
  record_file_name: ""
ieskf:
  cov_gyroscope: 0.1
  cov_acceleration: 0.1
  cov_bias_acceleration: 0.0001
  cov_bias_gyroscope: 0.0001
